routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('admin', functi
on () {
//     return view('index');
// });


Route::get('admin', function() {
    return view('utama');
});
use App\Http\Controllers\ProvinsiController;
Route::resource('admin/provinsi', ProvinsiController::class);

use App\Http\Controllers\KotaController;
Route::resource('admin/kota', KotaController::class);

use App\Http\Controllers\KecamatanController;
Route::resource('admin/kecamatan', KecamatanController::class);

use App\Http\Controllers\KelurahanController;
Route::resource('admin/kelurahan', KelurahanController::class);

use App\Http\Controllers\RwController;
Route::resource('admin/rw', RwController::class);

use App\Http\Controllers\KasusController;
Route::resource('admin/kasus', KasusController::class); 

use App\Http\Controllers\ReportController;
Route::resource('/', ReportController::class); 



Route::view('states-city','livewire.home');














Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Provinsi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Provinsi extends Model
{
    use HasFactory;

    protected $fillable = ['kode_provinsi','provinsi'];
    public $timestamps = true;

    public function kotaa()
    {
    	return $this->hasMany(Kota::class);
    }

}

app/Http/Controllers/Api/ProvinsiController.php
<?php

namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Provinsi;

class ProvinsiController extends Controller
{

    public function index(){

        $provinsi = Provinsi::all()->get();
        $res = [
            'success' => true,
            'data'    => $provinsi,
            'message' => 'Data Provinsi Ditampilkan'
        ];

        return response()->json($res,200);

    }
    
    public function store(Request $request)
    {
        $provinsi = new Provinsi();
        $provinsi->kode_provinsi = $request->kode_provinsi;
        $provinsi->provinsi = $request->provinsi;
        $provinsi->save();

        $res = [
            'success'=> true,
            'data' => $provinsi,
            'message' => 'data berhasil ditambah'
        ];
        return response()->json($res,200);
    }





    public function show($id)
    {
        $provinsi = Provinsi::whereId($id)->first();
        if($provinsi){
            $res = [
                'success'=> true,
                'data' => $provinsi,
                'message' => 'berhasil'
            ];
            return response()->json($res,200 );  

        }else{

            return response()->json([
                'success'=> false,
                'data' => '',
                'message' => 'Data Tidak Ada'
            ],400);

        }
    }
    // public function destroy($id)
    // {
    //     $provinsi = Provinsi::whereId($id)->first();
    //     if($provinsi){
    //         $provinsi->delete();
    //         $res = [
    //             'success'=> true,
    //             'data' => $provinsi,
    //             'message' => 'berhasil'
    //         ];
    //         return response()->json($res,200 );
    //     } else {
    //         return response()->json([
    //             'success'=>false,
    //             'data'=> '',
    //             'message'=>'data tidak ada'
    //         ],400);
    //     }
    // }
}

app/Http/Controllers/ProvinsiController.php
<?php

namespace App\Http\Controllers;
use App\Models\Provinsi;
use App\Http\Controllers\DB;
use Illuminate\Http\Request;

class ProvinsiController extends Controller
{
    
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(){
        
     $provinsi = Provinsi::all();
     return view('provinsi.index', compact('provinsi'));
    // return response()->json([
    //     'success' => true,
    //     'message' => 'Menampilkan Data',
    //     'data'    => $provinsi
    // ],400);
}
    

    public function create(){
        return view('provinsi.create');
    }

    public function store(Request $request)
    {
        //Validasi
        $validatedData = $request->validate([
            'kode_provinsi' => 'required',
            'provinsi' => 'required|max:255',
       ]);

        $provinsi = new Provinsi;
        $provinsi->kode_provinsi = $request->kode_provinsi;
        $provinsi->provinsi      = $request->provinsi;
        $provinsi->save();
        return redirect()->route('provinsi.index');
    }

    public function show($id)
    {
        $provinsi = Provinsi::findOrFail($id);
        return view('provinsi.show', compact('provinsi'));
    }

    public function edit($id)
    {
        $provinsi = Provinsi::findOrFail($id);
        return view('provinsi.edit', compact('provinsi'));
    }

    public function update(Request $request, $id)
    {
        $provinsi = Provinsi::findOrFail($id);
        $provinsi->kode_provinsi = $request->kode_provinsi;
        $provinsi->provinsi      = $request->provinsi;
        $provinsi->save();
        return redirect()->route('provinsi.index');
    }

    public function destroy($id)
        {
            $provinsi = Provinsi::findOrFail($id);
            $provinsi->delete();
            return redirect()->route('provinsi.index');
    }

    

}

resources/views/provinsi/create.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><b>Add Data Provinsi</b></div>
                <div class="card-body">
                  <!-- Form Create Data Provinsi -->
                <form action="{{route('provinsi.store')}}" method="POST">
                    @csrf
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Kode Provinsi</label>
                        <input type="text" name="kode_provinsi" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        <br>
                        @error('kode_provinsi')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Provinsi</label>
                        <input type="text" name="provinsi" class="form-control" id="exampleInputPassword1">
                        <br>
                        @error('provinsi')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Add Data</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/provinsi/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><b>Edit Data Provinsi</b></div>
                <div class="card-body">
                  <!-- Form Create Data Provinsi -->
                <form action="{{route('provinsi.update', $provinsi->id)}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Kode Provinsi</label>
                        <input type="text" name="kode_provinsi" value="{{$provinsi->kode_provinsi}}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        <br>
                        @error('kode_provinsi')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Provinsi</label>
                        <input type="text" name="provinsi" value="{{$provinsi->provinsi}}" class="form-control" id="exampleInputPassword1">
                        <br>
                        @error('provinsi')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Edit Data</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/provinsi/index.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Data Provinsi</div>

                <div class="card-body">
                  
                <a href="{{ route('provinsi.create') }}" class="btn btn-outline-success float-right"><b>Add Data</b></a>
                      <table class="table">
                      <thead>
                        <tr>
                          <th scope="col">No</th>
                          <th scope="col">Kode Provinsi</th>
                          <th scope="col">Provinsi</th>
                          <th scope="col">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                      @php $no = 1; @endphp
                     @foreach($provinsi as $data)
                        <tr>
                          <th scope="row">{{ $no++ }}</th>
                          <td>{{ $data->kode_provinsi }}</td>
                          <td>{{ $data->provinsi }}</td>
                          <form action="{{route('provinsi.destroy', $data->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                          <td>
                          <a href="{{route('provinsi.edit', $data->id)}}"class="btn btn-outline-primary float-right"><b>Edit</b></a>
                          <a href="{{route('provinsi.show', $data->id)}}" class="btn btn-outline-info float-right"><b>Detail</b></a>
                          <button type="submit" class="btn btn-outline-danger float-right">Delete</button>
                          </td>
                        </tr>
                        </form>
                        @endforeach
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/provinsi/show.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><b>Show Data Provinsi</b></div>
                <div class="card-body">
                  <!-- Form Create Data Provinsi -->
                <form action="" method="POST">
                    
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Kode Provinsi</label>
                        <input type="text" name="kode_provinsi" value="{{$provinsi->kode_provinsi}}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" disabled>
                        <br>
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Provinsi</label>
                        <input type="text" name="provinsi" value="{{$provinsi->provinsi}}" class="form-control" id="exampleInputPassword1" disabled>
                        <br>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection