routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('admin', functi
on () {
//     return view('index');
// });


Route::get('admin', function() {
    return view('utama');
});
use App\Http\Controllers\ProvinsiController;
Route::resource('admin/provinsi', ProvinsiController::class);

use App\Http\Controllers\KotaController;
Route::resource('admin/kota', KotaController::class);

use App\Http\Controllers\KecamatanController;
Route::resource('admin/kecamatan', KecamatanController::class);

use App\Http\Controllers\KelurahanController;
Route::resource('admin/kelurahan', KelurahanController::class);

use App\Http\Controllers\RwController;
Route::resource('admin/rw', RwController::class);

use App\Http\Controllers\KasusController;
Route::resource('admin/kasus', KasusController::class); 

use App\Http\Controllers\ReportController;
Route::resource('/', ReportController::class); 



Route::view('states-city','livewire.home');














Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Kelurahan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kelurahan extends Model
{
    use HasFactory;

    public function rww()
    {
    	return $this->hasMany(Rw::class);
    }

    public function kecamatann()
    {
    	return $this->BelongsTo(Kecamatan::class,'id_kecamatan');
    }
}

app/Http/Controllers/KelurahanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kecamatan;
use App\Models\Kelurahan;
use App\Http\Controllers\DB;
use Illuminate\Http\Request;

class KelurahanController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(){
        // $provinsi = Provinsi::all();
         // mengambil data dari table pegawai
        // $provinsi = DB::table('provinsi')->paginate(2);
        
        $kecamatan = Kecamatan::all();
        $kelurahan = Kelurahan::all();
        return view('kelurahan.index', compact('kelurahan','kecamatan'));
    }   

    public function create(){

        $kecamatan = Kecamatan::all();
        return view('kelurahan.create', compact('kecamatan'));
    }

    public function store(Request $request)
    {
        $kelurahan = new Kelurahan;
        $kelurahan->id_kecamatan = $request->id_kecamatan;
        $kelurahan->kelurahan = $request->kelurahan;
        $kelurahan->save();
        return redirect()->route('kelurahan.index')->with(['message' => 'Data kota Berhasil disimpan']);
    }

    public function edit($id)
    {
        $kelurahan = Kelurahan::findOrFail($id);
        $kecamatan = Kecamatan::all();
        return view('kelurahan.edit', compact('kelurahan','kecamatan'))->with(['message' => 'Data provinsi Berhasil diedit']);
    }

    public function update(Request $request, $id)
    {
        $kelurahan = Kelurahan::findOrFail($id);
        $kelurahan->id_kecamatan = $request->id_kecamatan;
        $kelurahan->kelurahan = $request->kelurahan;
        $kelurahan->save();
        return redirect()->route('kelurahan.index')->with(['message' => 'Data kota Berhasil disimpan']);
    }

    public function show($id)
    {
        $kelurahan = Kelurahan::findOrFail($id);
        $kecamatan = Kecamatan::all();
        return view('kelurahan.show', compact('kelurahan','kecamatan'));
    }

    public function destroy($id)
    {
        $kelurahan = Kelurahan::findOrFail($id);
        $kelurahan->delete();
        return redirect()->route('kelurahan.index')
                        ->with('success','Kota deleted successfully');
    }

}

resources/views/kelurahan/create.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><b>Add Data Kelurahan</b></div>
                <div class="card-body">
                  <!-- Form Create Data Provinsi -->
                <form action="{{route('kelurahan.store')}}" method="POST">
                    @csrf
                          <div class="mb-3">
                              <label for="disabledSelect" class="form-label">Kecamatan</label>
                              <select id="disabledSelect" class="form-control" name="id_kecamatan">
                              @foreach($kecamatan as $data)
                                <option value="{{$data->id}}">{{$data->kecamatan}}</option>
                              @endforeach
                              </select>
                          </div>
                          <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Kelurahan</label>
                                <input type="text" name ="kelurahan" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                           </div>
                      <button type="submit" class="btn btn-outline-success float-right">Add  Data</button>
              </form>
              </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kelurahan/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><b>Edit Data Kelurahan</b></div>
                <div class="card-body">
                  <!-- Form Create Data Provinsi -->
                <form action="{{route('kelurahan.update', $kelurahan->id)}}" method="POST">
                    @csrf
                    @method('PUT')
                          <div class="mb-3">
                              <label for="disabledSelect" class="form-label">Kecamatan</label>
                              <select id="disabledSelect" class="form-control" name="id_kecamatan">
                              @foreach($kecamatan as $data)
                                <option value="{{$data->id}}" {{ $data->id == $kelurahan->id_kecamatan ? 'selected' : '' }} >{{$data->kecamatan}}</option>
                              @endforeach
                              </select>
                          </div>
                          <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Kelurahan</label>
                                <input type="text" name ="kelurahan" value="{{ $kelurahan->kelurahan }}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                           </div>
                      <button type="submit" class="btn btn-outline-success float-right">Add  Data</button>
              </form>
              </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kelurahan/index.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Data Kelurahan</div>
                <div class="card-body">
                
                <a href="{{ route('kelurahan.create') }}" class="btn btn-outline-success float-right"><b>Add Data</b></a>
                  <table class="table">
                          <thead>
                              <tr>
                              <th scope="col">No</th>
                              <th scope="col">Kecamatan</th>
                              <th scope="col">Kelurahan</th>
                              <th scope="col">Action</th>
                              </tr>
                          </thead>
                          <tbody>
                          @php $no = 1; @endphp
                          @foreach($kelurahan as $data)
                              <tr>
                              <th scope="row">{{ $no++ }}</th>
                              <td>{{ $data->kecamatann->kecamatan }}</td>
                              <td>{{ $data->kelurahan }}</td>
                          <form action="{{route('kelurahan.destroy', $data->id)}}" method="post">
                              @csrf
                              @method('DELETE')
                              <td>
                              <a href="{{route('kelurahan.edit', $data->id)}}"class="btn btn-outline-primary float-right"><b>Edit</b></a>
                              <a href="{{route('kelurahan.show', $data->id)}}" class="btn btn-outline-info float-right"><b>Detail</b></a>
                              <button type="submit" class="btn btn-outline-danger float-right">Delete</button>
                              </td>
                              </tr>
                          </form>
                          @endforeach
                          </tbody>
                      </table>
                  </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kelurahan/show.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><b>Show Data Kelurahan</b></div>
                <div class="card-body">
                  <!-- Form Create Data Provinsi -->
                <form action="" method="POST">
                          <div class="mb-3">
                              <label for="disabledSelect" class="form-label">Provinsi</label>
                              <select id="disabledSelect" class="form-select" name="id_kecamatan">
                              @foreach($kecamatan as $data)
                                <option value="{{$data->id}}" {{ $data->id == $kelurahan->id_kecamatan ? 'selected' : '' }} >{{$data->kecamatan}}</option>
                              @endforeach
                              </select>
                          </div>
                          <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Kode Kota</label>
                                <input type="text" name ="kelurahan" value="{{ $kelurahan->kelurahan }}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                           </div>
              </form>
              </div>
            </div>
        </div>
    </div>
</div>
@endsection