routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('admin', functi
on () {
//     return view('index');
// });


Route::get('admin', function() {
    return view('utama');
});
use App\Http\Controllers\ProvinsiController;
Route::resource('admin/provinsi', ProvinsiController::class);

use App\Http\Controllers\KotaController;
Route::resource('admin/kota', KotaController::class);

use App\Http\Controllers\KecamatanController;
Route::resource('admin/kecamatan', KecamatanController::class);

use App\Http\Controllers\KelurahanController;
Route::resource('admin/kelurahan', KelurahanController::class);

use App\Http\Controllers\RwController;
Route::resource('admin/rw', RwController::class);

use App\Http\Controllers\KasusController;
Route::resource('admin/kasus', KasusController::class); 

use App\Http\Controllers\ReportController;
Route::resource('/', ReportController::class); 



Route::view('states-city','livewire.home');














Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Kecamatan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kecamatan extends Model
{
    use HasFactory;

    public function kelurahann()
    {
    	return $this->hasMany(Kelurahan::class);
    }

    public function kotaa()
    {
    	return $this->BelongsTo(Kota::class,'id_kota');
    }
}

app/Http/Controllers/KecamatanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kecamatan;
use App\Models\Kota;
use App\Http\Controllers\DB;
use Illuminate\Http\Request;

class KecamatanController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index() {

    $kota = Kota::all();
    $kecamatan = Kecamatan::paginate(5)->fragment('kecamatan');
    return view('kecamatan.index', compact('kecamatan','kota'));
    }

    public function create(){

        $kota = Kota::all();
        return view('kecamatan.create', compact('kota'));
    }

    public function store(Request $request)
    {
        $kecamatan = new Kecamatan;
        $kecamatan->id_kota = $request->id_kota;
        $kecamatan->kecamatan = $request->kecamatan;
        $kecamatan->save();
        return redirect()->route('kecamatan.index')->with(['message' => 'Data kecamatan Berhasil disimpan']);
    }

    public function show($id)
    {
        $kecamatan = Kecamatan::findOrFail($id);
        $kota = Kota::all();
        return view('kecamatan.show', compact('kecamatan','kota'))->with(['message' => 'Data provinsi Berhasil diedit']);
    }

    public function edit($id)
    {
        $kecamatan = Kecamatan::findOrFail($id);
        $kota = Kota::all();
        return view('kecamatan.edit', compact('kecamatan','kota'))->with(['message' => 'Data provinsi Berhasil diedit']);
    }

    public function update(Request $request, $id)
    {
        $kecamatan = Kecamatan::findOrFail($id);
        $kecamatan->id_kota = $request->id_kota;
        $kecamatan->kecamatan = $request->kecamatan;
        $kecamatan->save();
        return redirect()->route('kecamatan.index')->with(['message' => 'Data kota Berhasil disimpan']);
    }

    public function destroy($id)
    {
        $kecamatan = Kecamatan::findOrFail($id);
        $kecamatan->delete();
        return redirect()->route('kecamatan.index')
                        ->with('success','Kota deleted successfully');
    }

}

resources/views/kecamatan/create.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><b>Add Data Kecamatan</b></div>
                <div class="card-body">
                  <!-- Form Create Data Provinsi -->
                <form action="{{route('kecamatan.store')}}" method="POST">
                    @csrf
                          <div class="mb-3">
                              <label for="disabledSelect" class="form-label">Kota</label>
                              <select id="disabledSelect" class="form-control" name="id_kota">
                              @foreach($kota as $data)
                                <option value="{{$data->id}}">{{$data->kota}}</option>
                              @endforeach
                              </select>
                          </div>
                          <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Kecamatan</label>
                                <input type="text" name ="kecamatan" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                           </div>
                      <button type="submit" class="btn btn-outline-success float-right">Add  Data</button>
              </form>
              </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kecamatan/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><b>Edit Data Kecamatan</b></div>
                <div class="card-body">
                  <!-- Form Create Data Provinsi -->
                <form action="{{route('kecamatan.update', $kecamatan->id)}}" method="POST">
                    @csrf
                    @method('PUT')
                          <div class="mb-3">
                              <label for="disabledSelect" class="form-label">Kota</label>
                              <select id="disabledSelect" class="form-control" name="id_kota">
                              @foreach($kota as $data)
                                <option value="{{$data->id}}" {{ $data->id == $kecamatan->id_kota ? 'selected' : '' }} >{{$data->kota}}</option>
                              @endforeach
                              </select>
                          </div>
                          <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Kecamatan</label>
                                <input type="text" name ="kecamatan" value="{{ $kecamatan->kecamatan }}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                           </div>
                      <button type="submit" class="btn btn-outline-success float-right">Edit  Data</button>
              </form>
              </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kecamatan/index.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Data Kecamatan</div>
                <div class="card-body">
                
                <a href="{{ route('kecamatan.create') }}" class="btn btn-outline-success float-right"><b>Add Data</b></a>

                <table class="table">
                        <thead>
                            <tr>
                            <th scope="col">No</th>
                            <th scope="col">Kota</th>
                            <th scope="col">Kecamatan</th>
                            <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        @php    $no = 1;    @endphp
                        @foreach ($kecamatan as $data)
                            <tr>
                            <th scope="row">{{ $data->id }}</th>
                            <td>{{ $data->kotaa->kota }}</td>
                            <td>{{ $data->kecamatan }}</td>
                            <td></td>
                        <form action="{{route('kecamatan.destroy', $data->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <td>
                            <a href="{{ route('kecamatan.edit', $data->id) }}"class="btn btn-outline-primary float-right"><b>Edit</b></a>
                            <a href="{{ route('kecamatan.show', $data->id) }}" class="btn btn-outline-info float-right"><b>Detail</b></a>
                            <button type="submit" class="btn btn-outline-danger float-right">Delete</button>
                            </td>
                            </tr>
                        </form>
                    @endforeach
                        </tbody>
                    </table>
                  </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kecamatan/show.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><b>Edit Data Kecamatan</b></div>
                <div class="card-body">
                  <!-- Form Create Data Provinsi -->
                <form action="" method="POST">
                          <div class="mb-3">
                              <label for="disabledSelect" class="form-label">Kota</label>
                              <select id="disabledSelect" class="form-select" name="id_kota">
                              @foreach($kota as $data)
                                <option value="{{$data->id}}" {{ $data->id == $kecamatan->id_kota ? 'selected' : '' }} >{{$data->kota}}</option>
                              @endforeach
                              </select>
                          </div>
                          <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Kecamatan</label>
                                <input type="text" name ="kecamatan" value="{{ $kecamatan->kecamatan }}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                           </div>
                      </form>
              </div>
            </div>
        </div>
    </div>
</div>
@endsection